name = "Napari"
uuid = "ed46c112-542a-4e7e-ab0f-e39321fab6f0"
authors = ["Mark Kittisopikul <markkitt@gmail.com> and contributors"]
version = "0.2.1"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageMetadata = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
NumPyArrays = "359eecd2-3036-4797-89e9-498f868f96c0"
OMETIFF = "2d0ec36b-e807-5756-994b-45af29551fcf"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[compat]
AxisArrays = "0.4"
ColorTypes = "0.10.9, 0.11"
Conda = "1.5.0"
FixedPointNumbers = "0.8.4"
ImageIO = "0.4, 0.5, 0.6"
ImageMagick = "1.1"
ImageMetadata = "0.9"
Images = "0.23.3, 0.24, 0.25"
NumPyArrays = "0.1.1"
OMETIFF = "0.3, 0.4"
PyCall = "1.92"
TestImages = "1.3.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["Test", "TestImages"]
